# Introduction to PyTorch

This tutorial shows the basics of PyTorch library.

We design simple Neural Networks for classification task on MNIST dataset.

Necessary knowledge you can find in PyTorch documentation:

https://pytorch.org/docs/stable/index.html

and tutorials:

https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

Of course you can use also Google ;)

https://github.com/MichalMachura/AGH-EmbeddedAI

In [ ]:
!mkdir data

1. PyTorch is based on tensor operations.

Please create tensors in the following ways:
(for all cases use `shape = (1, 3, 28, 28)` - (batch_size, channels, height, width).)

a) directly with python list (with any shape) - 

b) based on numpy array with `shape` - `torch.from_numpy`

c) with random values (initialize generator with your academic id / student number from USOS system) -

`torch.manual_seed`,`torch.rand`

d) linear space in range from -5 to 15 and number of elements to achieve `shape` - `torch.linspace`

e) 3 tensors (`x1,x2,x2`) with indices of each element of grid for dimensions: 1, 2, 3 (without 0-th - basically it's a batch dimension) - `torch.meshgrid`

For display use `print` function.

In [3]:
import torch
import numpy as np
shape = (1,3,28,28)

# a
t = torch.tensor([3243.4, 44.2, 4242.4], dtype=torch.float32)
print(t)
# b
a = np.random.rand(*shape)
t = torch.from_numpy(a)
print(t)
# c
torch.manual_seed(43543)
t = torch.rand(shape)
print(t)
# d
t = torch.linspace(-5,15, shape[0]*shape[1]*shape[2]*shape[3]).reshape(shape)
print(t)
# e
x0 = torch.arange(shape[0])
x1 = torch.arange(shape[1])
x2 = torch.arange(shape[2])
x3 = torch.arange(shape[3])
x0, x1, x2, x3 = torch.meshgrid(x0,x1,x2,x3)
print(x0)
print(x1)
print(x2)
print(x3)

tensor([3243.3999,   44.2000, 4242.3999])
tensor([[[[0.8923, 0.1496, 0.6169,  ..., 0.3385, 0.9233, 0.1986],
          [0.4675, 0.5498, 0.4347,  ..., 0.5428, 0.0798, 0.9068],
          [0.3385, 0.4136, 0.1666,  ..., 0.5802, 0.3332, 0.7005],
          ...,
          [0.3493, 0.0746, 0.4280,  ..., 0.3730, 0.8603, 0.8630],
          [0.3617, 0.5209, 0.7110,  ..., 0.9962, 0.9313, 0.0066],
          [0.3867, 0.6721, 0.9795,  ..., 0.6605, 0.6939, 0.7924]],

         [[0.0058, 0.4261, 0.6261,  ..., 0.6547, 0.0771, 0.2977],
          [0.5396, 0.8143, 0.4989,  ..., 0.7205, 0.4818, 0.7665],
          [0.0960, 0.8016, 0.5131,  ..., 0.0339, 0.6216, 0.0434],
          ...,
          [0.0928, 0.9321, 0.3156,  ..., 0.3496, 0.6269, 0.1172],
          [0.6237, 0.2330, 0.2168,  ..., 0.1342, 0.0200, 0.7097],
          [0.9882, 0.4323, 0.0363,  ..., 0.9289, 0.7874, 0.6920]],

         [[0.6516, 0.6148, 0.4989,  ..., 0.5707, 0.8747, 0.9217],
          [0.5437, 0.8809, 0.5970,  ..., 0.0785, 0.9608, 0.8054],


/home/michal/.local/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


2. PyTorch allow for applying GPU for computations.
Check if gpu (CUDA) is available, then use it as `device`, else use `'cpu'`.

In [6]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)
t = torch.tensor([43,43], device=device)
print(t)

cuda
tensor([43, 43], device='cuda:0')


3. To train a networks we need a dataset. 

Please download `MINIST` dataset with `torchvision.dataset`.

For any kind of ML tasks, validation and/or testing is required.

So, create train and test datasets.

For train dataset apply also augmentation transforms, crop, translation and rotation.

You can try to apply different transforms.

For both apply ToTensor.

Next, pack datasets into `DataLoader`s with batch size of 64.
Use variables with names: `train_loader` and `test_loader`. 

Next display sizes of datasets, shapes of elements and display few images (`plt.gray()`,`plt.imshow()`) and their labels.

In [ ]:
import torch
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

test_dataset = ...
train_dataset = ...
...

train_loader = ...
test_loader = ...


4. `*`Additionally, you can prepare analysis of datasets. 

E.g. statistics like mean and variance of all elements, for each label.

Analysis can allow you for designing better network architecture.   

In [ ]:
...

5. When we have datasets, we can create model for classification task.

Please, define class `MLP` as Multi Layer Perceptron 

with two hidden fully connected layers with bias.

Class must inherits from `torch.nn.Module`.

Apply following configuration:

- first with 512 neurons,
- second with 512 neurons,
- output layer adjust to size of classification problem.

For `__init__` method add parameters: input_shape and output_size.

Hidden layers sizes can also be parametrized. 

Don't forget about nonlinearities! 

For hidden layers you can use `ReLU` module from `torch.nn`.

For output apply softmax function / layers.

Network layer-by-layer processing define in `forward` method with argument as a network 

input tensor - batch of images with shape (batch_size, channels, height, width).
(channels = 1, for gray scale images)

Instantiate model as `net` object.


In [ ]:

class MLP(...):

    def __init__(self, ) -> None:
        super().__init__()
        ...
        
    def forward(sefl, x: torch.Tensor) -> torch.Tensor:
        pass


net = ...

6. To train network we need to know 'how good or bad' results it gives.
Please, instantiate `torch.nn.CrossEntropyLoss` as `loss_fcn`.

7. To score network define accuracy metric.

For network output you need to decide what is the final network answer(`argmax`).

`torch.no_grad()` prevents gradient requirement for computations inside method.

In [ ]:
from abc import ABC, abstractmethod
from typing import Any


class BaseMetic(ABC):

    @abstractmethod
    def __call__(self, y_pred, y_ref) -> Any:
        raise NotImplementedError()    
    
    
class AccuracyMetic(BaseMetic):

    def __init__(self) -> None:
        pass
    
    @torch.no_grad()
    def __call__(self, y_pred: torch.Tensor, y_ref: torch.Tensor) -> torch.Tensor:
        """
        :param y_pred: tensor of shape (batch_size, num_of_classes) type float
        :param y_ref: tensor with shape (batch_size,) and type Long
        :return: scalar tensor with accuracy metric for batch
        """
        # scalar value
        score: torch.Tensor = ...
        
        return score


metric = AccuracyMetic()

8. To change network parameters, we need optimizers object.
Instantiate `torch.optim.SGD` (with `net`work parameters) as `optimizer`.
Use learning rate = 0.001

In [ ]:
optimizer = ...

9. Now define training / testing function:

Util functions: `tensor.backward`, `torch.nn.module()`

In [ ]:
from typing import Tuple
import tqdm


def train(model, 
          data_generator, 
          criterion, 
          metric: BaseMetic,
          optimizer: torch.optim.Optimizer = None, 
          update_period: int = None,
          mode: str = 'test',
          device = torch.device('cpu')) -> Tuple[torch.nn.Module, float, float]:
    
    # change model mode to train or test
    if mode == 'train':
        ...
        
    elif mode == 'test':
        ...
        
    else:
        raise RuntimeError("Unsupported mode.")

    # move model to device
    
    # reset model parameters' gradients with optimizer
    if mode == 'train':
        ...
    
    total_loss: float = 0.0
    total_accuracy: float = 0.0
    samples_num: int = 0
    
    for i, (X, y) in tqdm.tqdm(enumerate(data_generator)):
        # convert tensors to device
        ...
        
        # depending on mode use or not torch.no_grad() as 'with' block
        ...
        
        # process by network
        y_pred = ...
        
        # calculate loss
        loss = ...
        
        # designate gradient based on loss
        ...
        
        if mode == 'train' and (i+1) % update_period:
            # update parameters with optimizer
            ...
        
        # calculate accuracy
        accuracy = ...
        
        total_loss += loss.item() * y_pred.shape[0]
        total_accuracy += accuracy.item() * y_pred.shape[0]
        samples_num += y_pred.shape[0]
    
    if samples_num == 0:
        return model, 0.0, 0.0
    
    return model, total_loss / samples_num, total_accuracy / samples_num

10. Prepare training loop (over epochs) function:
- adjust max number of epochs to achieve satisfactory results.
- `**` additionally, implement auto-detection of bias-variance tradeoff point, to break further training.
- `***` additionally, use learning rate scheduler.
- for each epoch collect losses and accuracies for both datasets.

In [ ]:
...

11. Display training history (`plt.plot`). 

12. Save model and optimizer states to files.

Use method `state_dict` and function `torch.save`.

In [ ]:
...

13. Create new network with the same architecture and initialize it with saved weights.

`torch.load`, `load_state_dict`.

In [ ]:
net2 = ...
...

14. Define your own model and train it.

Try achieve better results.

You can use different parameters, layers e.g.:
- conv2d
- maxpooling2d
- batch norm 2d
- and more...

Save weights to file.

In [ ]:
...

15. You can leave a feedback, if you want :)

16. Send (e-mail) your results(notebook+weights) in a *.zip file

or (preferred) send link to your's github repository with your results.